/**
 * @module tools/creative/types
 *
 * Type definitions for the creative generation and management tool suite.
 * These types define the data structures used across all creative tools,
 * including ad copy variations, performance analysis results, image prompt
 * specifications, and the extended tool context required for LLM and Meta
 * API access.
 */

import type { LLMProvider } from "../../llm/types.js";
import type { ToolContext } from "../types.js";

/**
 * MetaClient interface for creative tools.
 *
 * Declares the subset of the MetaClient facade that creative tools depend on.
 * This avoids a hard package dependency on @meta-ads-agent/meta-client while
 * preserving full type safety. Consumers inject the real MetaClient at runtime.
 */
export interface MetaClientLike {
	/** Creative CRUD operations. */
	readonly creatives: {
		create(adAccountId: string, params: CreateCreativeInput): Promise<{ id: string; name: string }>;
		list(
			adAccountId: string,
		): Promise<Array<{ id: string; name: string; body?: string; title?: string }>>;
		get(creativeId: string): Promise<{
			id: string;
			name: string;
			body?: string;
			title?: string;
			call_to_action_type?: string;
			link_url?: string;
		}>;
		delete(creativeId: string): Promise<void>;
	};

	/** Ad operations for pausing/activating ads by creative. */
	readonly ads: {
		list(
			adAccountId: string,
		): Promise<
			Array<{ id: string; name: string; adset_id: string; status: string; creative_id: string }>
		>;
		update(adId: string, params: { status?: string }): Promise<{ id: string; status: string }>;
	};

	/** Insights queries for performance analysis. */
	readonly insights: {
		query(adAccountId: string, params: InsightsQueryInput): Promise<InsightsResultLike[]>;
	};
}

/**
 * Minimal creative creation parameters matching @meta-ads-agent/meta-client.
 */
export interface CreateCreativeInput {
	name: string;
	body?: string;
	title?: string;
	link_url?: string;
	image_hash?: string;
	video_id?: string;
	call_to_action_type?: string;
	object_story_spec?: { page_id: string; link_data?: Record<string, unknown> };
}

/**
 * Minimal insights query parameters matching @meta-ads-agent/meta-client.
 */
export interface InsightsQueryInput {
	level: "account" | "campaign" | "adset" | "ad";
	date_preset?: string;
	fields?: string[];
	filtering?: Array<{ field: string; operator: string; value: string | string[] }>;
}

/**
 * Minimal insights result matching @meta-ads-agent/meta-client.
 */
export interface InsightsResultLike {
	ad_id?: string;
	ad_name?: string;
	campaign_id?: string;
	impressions: string;
	clicks: string;
	spend: string;
	ctr: string;
	cpm: string;
	actions?: Array<{ action_type: string; value: string }>;
	date_start: string;
	date_stop: string;
}

/**
 * Extended tool context that provides LLM and Meta API access to creative tools.
 *
 * Creative tools require both an LLM provider (for generating copy and image
 * prompts) and a MetaClient (for creating/reading creatives and insights).
 * This interface extends the base ToolContext with those dependencies.
 */
export interface CreativeToolContext extends Omit<ToolContext, "metaClient" | "llmProvider"> {
	/** LLM provider for generating ad copy and image prompts. */
	readonly llmProvider: LLMProvider;

	/** Meta advertising client for creative and insights operations. */
	readonly metaClient: MetaClientLike;
}

/**
 * A single ad copy variation generated by the LLM.
 *
 * Each variation includes headline, body, CTA, and an image generation prompt.
 * Character limits follow Meta's ad specifications:
 * - Headline: 40 characters maximum
 * - Body: 125 characters maximum
 */
export interface AdCopyVariation {
	/** Headline text (40 characters maximum). */
	headline: string;

	/** Primary body text (125 characters maximum). */
	body: string;

	/** Call-to-action label (e.g., "Shop Now", "Learn More", "Sign Up"). */
	callToAction: string;

	/** Prompt for AI image generation tools (DALL-E, Midjourney, Ideogram). */
	imagePrompt: string;

	/** Tone used for this variation. */
	tone: string;
}

/**
 * Performance analysis result for a single creative.
 *
 * Contains raw metrics, a composite score, and a recommendation for
 * whether to keep, rotate, or retire the creative.
 */
export interface CreativePerformanceAnalysis {
	/** Meta creative identifier. */
	creativeId: string;

	/** Click-through rate as a decimal. */
	ctr: number;

	/** Cost per mille (cost per 1,000 impressions). */
	cpm: number;

	/** Average ad frequency (impressions per unique user). */
	frequency: number;

	/** Total conversion count. */
	conversions: number;

	/** Composite score: CTR * conversions / frequency. */
	score: number;

	/** Recommended action based on performance analysis. */
	recommendation: "keep" | "rotate" | "retire";
}

/**
 * Structured image generation prompt suitable for AI image tools.
 *
 * Contains all the information needed for DALL-E, Midjourney, or Ideogram
 * to generate an ad-appropriate image.
 */
export interface ImagePromptSpec {
	/** Primary generation prompt describing the desired image. */
	mainPrompt: string;

	/** Negative prompt listing elements to avoid. */
	negativePrompt: string;

	/** Aspect ratio for the generated image (e.g., "1:1", "16:9", "9:16"). */
	aspectRatio: string;

	/** Style notes for the image generation model. */
	styleNotes: string;
}

/**
 * State record for creative rotation tracking.
 *
 * Stored in the database to maintain rotation state across agent ticks.
 */
export interface RotationState {
	/** Ad set being managed. */
	adSetId: string;

	/** Ordered list of creative IDs in the rotation pool. */
	creativeIds: string[];

	/** Index of the currently active creative in the pool. */
	currentIndex: number;

	/** Reason for the last rotation. */
	lastRotationReason: string;

	/** ISO 8601 timestamp of the last rotation. */
	lastRotatedAt: string;
}
